services:
 matlab:
    container_name: matlab-script
    image: matlab-login
    ports:
     - "8888:8888"
     - "12345:12345"  # Added TCP server port
    volumes:
     - ./scripts:/home/matlab/Documents/MATLAB
    tty: true
    stdin_open: true
    networks:
      - matlab-net

 matlab-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/result/src           # Mount the local src directory
      - ./target:/result/target       # Mount the local target directory
      - ./mvnw:/result/mvnw           # Mount the mvnw script
      - ./pom.xml:/result/pom.xml     # Mount the pom.xml if needed
    ports:
      - "8087:8087"                     # Map port 8091 to the host
    environment:
      SPRING_PROFILES_ACTIVE: dev 
    depends_on:
      - matlab                          # Wait for MATLAB container to start
    networks:
      - matlab-net
      - rabbitmq-net
 rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672' # RabbitMQ Management UI
    networks:
      - rabbitmq-net

networks:
  matlab-net:
    driver: bridge
  rabbitmq-net:
    driver: bridge