classdef VisadevDeviceProvider < matlab.hwmgr.internal.DeviceProviderBase
    %DEVICEPROVIDER implements DeviceProviderBase abstract methods
    %  to return enumerable and non-enumerable devices. visadev app has
    %  both enumerable and non-enumerable devices.

    % Copyright 2022-2023 The MathWorks, Inc.

    properties
        VisaDeviceDescriptor
    end

    methods
        function devices = getDevices(~)
            devices = ...
                transportapp.visadev.internal.VisadevIdentification.getHwMgrDevice();
        end

        function descriptor = getDeviceParamDescriptors(obj)
            % If deviceParamDescriptor has not been created, create it.
            if isempty(obj.VisaDeviceDescriptor)
                createVisaDeviceDescriptor(obj);
            end

            descriptor = obj.VisaDeviceDescriptor;
        end

        function createVisaDeviceDescriptor(obj)
            descriptor = transportapp.visadev.internal.VisadevDescriptor();

            fieldLabel = @(msgLabel) message("transportapp:visadevapp:" + msgLabel).getString();
            sectionLabel = @(labelName) message("transportapp:visadevapp:" + labelName + "Section").getString();

            % Interface Dropdown
            descriptor.addParameter('Interface', ...
                fieldLabel("Interface"), ...
                "DropDown", ...
                @descriptor.interfaceValuesFcn, ...
                function_handle.empty, ...
                sectionLabel("Interface"));

            % Generate Resource String Button
            icon = matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository. ...
                getIcon("ict","Settings");
            descriptor.addButton('GenerateResourceName', ...
                fieldLabel("GenerateResourceName"), ...
                icon, ...
                'Vertical', ...
                @descriptor.generateResourceNameValuesFcn, ...
                @descriptor.generateResourceNameEnableFcn, ...
                sectionLabel("Interface"));

            % Resource Name Edit Field
            descriptor.addParameter('ResourceName', ...
                fieldLabel("ResourceName"), ...
                "EditField", ...
                @descriptor.generateResourceNameChangeFcn, ...
                function_handle.empty, ...
                sectionLabel("Resource"));

            % IdentificationString Edit Field
            descriptor.addParameter('Identification', ...
                fieldLabel("IdentificationName"), ...
                "EditField", ...
                @descriptor.identificationFcn, ...
                function_handle.empty, ...
                sectionLabel("TestConnection"));

            % Test Connection Button
            icon = matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository. ...
                getIcon("ict", "VisaTestConnection");
            descriptor.addButton('TestConnection', ...
                fieldLabel("TestConnection"), ...
                icon, ...
                'Vertical', ...
                @descriptor.testConnectionValuesFcn, ...
                function_handle.empty, ...
                sectionLabel("TestConnection"));

            % Model Edit Field
            descriptor.addParameter('Model', ...
                fieldLabel("Model"), ...
                "NonEditableField", ...
                function_handle.empty, ...
                function_handle.empty, ...
                sectionLabel("TestConnection"));

            % Vendor ID Edit Field
            descriptor.addParameter('Vendor', ...
                fieldLabel("VendorID"), ...
                "NonEditableField", ...
                function_handle.empty, ...
                function_handle.empty, ...
                sectionLabel("TestConnection"));

            % Connection Status Edit Field
            descriptor.addParameter('ConnectionStatus', ...
                fieldLabel("ConnectionStatus"), ...
                "NonEditableField", ...
                function_handle.empty, ...
                function_handle.empty, ...
                sectionLabel("TestConnection"));

            obj.VisaDeviceDescriptor = descriptor;
        end

    end
end
