classdef Constants
    %CONSTANTS contains View constant properties for the appspace Log panels.

    % Copyright 2023 The MathWorks, Inc.

    %% UI element properties
    properties (Constant)
        ActivityLogLayout = matlabshared.transportapp.internal.utilities.forms.AppSpaceGridLayout(2, 2:3)
        CodeLogLayout = matlabshared.transportapp.internal.utilities.forms.AppSpaceGridLayout(1, 3)
        ActivityLogPanelProps = struct("Title", message("ividevapp:ividevapp:ActivityLogSectionTitle").string, ...
            "TitlePosition", "lefttop", ...
            "FontSize", 12, ...
            "FontWeight", "bold")
        CodeLogPanelProps = struct("Title", message("ividevapp:ividevapp:MATLABCodeLogSectionTitle").string, ...
            "TitlePosition", "lefttop", ...
            "FontSize", 12, ...
            "FontWeight", "bold")
        TableProperties = struct( ...
            "RowName", {cell.empty}, ...
            "ColumnEditable", [false, false, false, false, false, false], ...
            "ColumnName", [message("ividevapp:ividevapp:IndexColumn").string, message("ividevapp:ividevapp:FuncPropColumn").string, ...
            message("ividevapp:ividevapp:InputNameColumn").string, message("ividevapp:ividevapp:InputValueColumn").string, ...
            message("ividevapp:ividevapp:OutputNameColumn").string, message("ividevapp:ividevapp:OutputValueColumn").string], ...
            "FontSize", 12, ...
            "ColumnWidth", ["1x", "7x", "5x", "7x", "5x", "7x"], ...
            "RowStriping", "off", ...
            "SelectionType", "cell", ...
            "Tag", "ActivityLogTable")
        LogsGridProperties = struct( ...
            "ColumnWidth", {"1x"}, ...
            "RowHeight", {"1x"}, ...
            "Padding", [0 0 0 0])
    end
end