classdef Constants
    %CONSTANTS contains View constant properties for the toolstrip Export section.

    % Copyright 2023 The MathWorks, Inc.
    
    properties (Constant)
        Position = matlabshared.transportapp.internal.utilities.forms.ToolstripColumn(90, "center")

        WorkspaceVariableLabelProps = struct("Text", message("ividevapp:ividevapp:ExportVariableLabel").string, ...
            "Description", matlabshared.transportapp.internal.toolstrip.export.Constants.WorkspaceVariableTooltip)

        ExportButtonProps = struct("Text", matlabshared.transportapp.internal.toolstrip.export.Constants.ExportButtonLabel, ...
            "Icon", matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("ict", "ExportButton"), ...
            "Description", message("ividevapp:ividevapp:ExportButtonTooltip").string, ...
            "Enabled", true, ...
            "Tag", 'ExportButton')

        ActivityLogListProps = struct("Text", message("ividevapp:ividevapp:ExportActivityLogLabel").string, ...
            "Icon", matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("ict", "ExportTable"), ...
            "Description", message("ividevapp:ividevapp:ExportActivityLogDescription").string, ...
            "Enabled", true, ...
            "Tag", 'ExportActivityLogButton')

        ActivityLogSelectedCellListProps = struct("Text", message("ividevapp:ividevapp:ExportActivityLogCellLabel").string, ...
            "Icon", matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("ict", "ExportRow"), ...
            "Description", message("ividevapp:ividevapp:ExportActivityLogCellDescription").string, ...
            "Enabled", true, ...
            "Tag", 'ExportCellButton')

        ExportCodeListProps = struct("Text", message("ividevapp:ividevapp:ExportMATLABCodeLogLabel").string, ...
            "Icon", matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("ict", "ExportScript"), ...
            "Description", message("ividevapp:ividevapp:ExportMATLABCodeLogDescription").string, ...
            "Enabled", true, ...
            "Tag", 'ExportCodeLogButton')
    end
end

