classdef Constants
    % CONSTANTS contains constants for the Communication log section used in
    % the UDP app communicating in datagram mode.

    % Copyright 2021 The MathWorks, Inc.

    properties (Constant)
        TableParentGrid = struct( ...
            'ColumnWidth', "1x", ...
            'RowHeight', "1x", ...
            'Padding', [0, 0, 0, 0] ...
            )

        % Include an Address and Port column when in datagram mode.
        ColumnNames = ["Action", "Address and Port", "Data", "Size", "Data Type", "Time"]

        Table = struct( ...
            'RowName', {cell.empty}, ...
            'ColumnEditable', false(1,5), ...
            'ColumnName', transportapp.udpport.internal.datagram.appspace.communicationlog.Constants.ColumnNames', ...
            'FontSize', 12, ...
            'ColumnWidth', ["2x", "6x", "20x", "2x", "3x", "4x"], ...
            'RowStriping', 'off', ...
            "Tag", 'CommunicationLogTable')

        DataColumn = 3
        SizeColumn = 4
        RowDataDelimiter = " "

        ContextMenuLabels = string(message("transportapp:toolstrip:export:SelectedRowButtonLabel").getString)
    end
end
