classdef Constants
    %CONSTANTS contains View constant properties for the toolstrip Analyze section.

    % Copyright 2023 The MathWorks, Inc.
    
    properties (Constant)
        Position = matlabshared.transportapp.internal.utilities.forms.ToolstripColumn(50, "center")

        PlotButtonProps = struct("Text", message("ividevapp:ividevapp:PlotButtonLabel").string,...
            "Icon", matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("ict", "Plot"), ...
            "Description", message("ividevapp:ividevapp:PlotButtonTooltip").string, ...
            "Enabled", true, ...
            "Tag", 'PlotButton')

        SignalAnalyzerButtonProps = struct("Text", matlabshared.transportapp.internal.toolstrip.analyze.Constants.SigAnButtonLabel,...
            "Icon", matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("ict", "SignalAnalyzer"), ...
            "Description", message("ividevapp:ividevapp:SigAnButtonTooltip").string, ...
            "Enabled", true, ...
            "Tag", 'SigAnalyzerButton')
        
        ClearButtonProps = struct("Text", message("ividevapp:ividevapp:ClearLogButtonLabel").string, ...
            "Icon", matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("ict", "Clear"), ...
            "Description", message("ividevapp:ividevapp:ClearLogButtonTooltip").string, ...
            "Enabled", true, ...
            "Tag", 'ClearButton')
    end
end

