classdef ExistingMethodCodeType
    %EXISTINGMETHODCODETYPE is the list of Driver functions where the code
    %for evaluating the function is not present in the MDD, but is
    %hard-coded.

    %   Copyright 2022-2023 The MathWorks, Inc.

    enumeration
        Init
        InitWithOptions
        Close
        DeviceReset
        GetError
        SelfTest
    end

    methods (Static)
        function code = getCodeForInit(resourceName, driverName)

            %Check to see if it is an niDCPower driver. If so, the Init
            %code is different and needs to be adjusted accordingly.
            if driverName == "niDCPower"
                code = ...
                    "function [status, session] = init" + newline ...
                    + "rsrc = [double('" + resourceName + "') 0];" + newline ...
                    + "channel = [double('') 0];" + newline ...
                    + "optionString = [double('') 0];" + newline ...
                    + "InstrumentHandle = libpointer('uint32Ptr' ,0);" + newline ...
                    + "[status, dummy, session] = calllib('" + driverName ...
                    + "', '" + driverName + "_InitializeWithChannels', rsrc, channel, true, optionString, InstrumentHandle);" + newline ...
                    + "if status < 0 " + newline ...
                    + "[status, dummy, session] = calllib('" + driverName ...
                    + "', '" + driverName + "_InitializeWithChannels', rsrc, channel, true, optionString, InstrumentHandle);" + newline ...
                    + "end" + newline ...
                    + "session = uint32(InstrumentHandle.Value);";
            else
                code = ...
                    "function [status, session] = init" + newline ...
                    + "rsrc = [double('" + resourceName + "') 0];" + newline  ...
                    + "InstrumentHandle = libpointer('uint32Ptr' ,0);" + newline  ...
                    + "[status, dummy, session] = calllib('" + driverName ...
                    + "', '" + driverName + "_init', rsrc, false, false, InstrumentHandle);" + newline  ...
                    + "if status < 0 " + newline  ...
                    + "[status, dummy, session] = calllib('" + driverName ...
                    + "', '" + driverName + "_init', rsrc, false, true, InstrumentHandle);" + newline  ...
                    + "end" + newline  ...
                    + "session = uint32(InstrumentHandle.Value);";
            end
        end

        function code = getCodeForInitWithOptions(resourceName, optionString, driverName)
            if isempty(optionString)
                optionString = "";
            end

            %Check to see if it is an niDCPower driver. If so, the InitWithOptions
            %code is different and needs to be adjusted accordingly.
            if driverName == "niDCPower"
                code = ...
                    "function [status, session] = init" + newline ...
                    + "rsrc = [double('" + resourceName + "') 0];" + newline ...
                    + "channel = [double('') 0];" + newline ...
                    + "optionString = [double('" + optionString + "') 0];" + newline ...
                    + "InstrumentHandle = libpointer('uint32Ptr' ,0);" + newline ...
                    + "[status, dummy, session] = calllib('" + driverName ...
                    + "', '" + driverName + "_InitializeWithChannels', rsrc, channel, true, optionString, InstrumentHandle);" + newline ...
                    + "if status < 0 " + newline ...
                    + "[status, dummy, session] = calllib('" + driverName ...
                    + "', '" + driverName + "_InitializeWithChannels', rsrc, channel, true, optionString, InstrumentHandle);" + newline ...
                    + "end" + newline ...
                    + "session = uint32(InstrumentHandle.Value);";
            else
                code = ...
                    "function [status, session] = init" + newline  ...
                    + "rsrc = [double('" + resourceName + "') 0];" + newline  ...
                    + "optionString = [double('" + optionString + "') 0];" + newline  ...
                    + "InstrumentHandle = libpointer('uint32Ptr' ,0);" + newline  ...
                    + "[status, dummy, session] = calllib('" + driverName ...
                    + "', '" + driverName + "_InitWithOptions', rsrc, false, false, optionString, InstrumentHandle);" + newline  ...
                    + "if status < 0 " + newline  ...
                    + "[status, dummy, session] = calllib('" + driverName ...
                    + "', '" + driverName + "_InitWithOptions', rsrc, false, true, optionString, InstrumentHandle);" + newline  ...
                    + "end" + newline  ...
                    + "session = uint32(InstrumentHandle.Value);";
            end
        end

        function code = getCodeForClose(driverName)
            code = "function status = close" + newline ...
                + "session = get(obj, 'Interface');" + newline ...
                + "status = calllib('" + driverName + "', '" + driverName ...
                + "_close', session);" + newline;
        end

        function code = getCodeForDeviceReset(driverName)
            code = "function devicereset(obj)" + newline ...
                + "session = get(obj, 'Interface');" + newline ...
                + "status = calllib('" + driverName + "', '" ...
                + driverName + "_reset', session);";
        end

        function code = getCodeForGetError(driverName)
            code = "function msg = geterror(obj)" + newline ...
                + "session = get(obj, 'Interface');" + newline ...
                + "msg = libpointer('int8Ptr', repmat(10, 1, 1024));" + newline ...
                + "[status, code] = calllib('" + driverName + "', '" ...
                + driverName + "_error_query', session, 0, msg);" + newline ...
                + "msg = strtrim(char(msg.Value));";
        end

        function code = getCodeForSelfTest(driverName)
            code = "function msg = getError(obj)" + newline ...
                + "session = get(obj, 'Interface');" + newline ...
                + "msg = libpointer('int8Ptr', repmat(10, 1, 1024));" + newline ...
                + "status = calllib('" + driverName + "', '" ...
                + driverName + "_self_test', session, 0, msg);" + newline ...
                + "msg = strtrim(char(msg.Value));";
        end
    end
end
