classdef IvidevDeviceProvider < matlab.hwmgr.internal.DeviceProviderBase
    % IVIDEVDEVICEPROVIDER is realizing the Hardware Manager interface
    % 'DeviceProviderBase'.

    % Copyright 2023-2024 The MathWorks, Inc.

    properties
        NonEnumDescriptor
        DetectedDeviceDescriptor
    end

    properties (Constant)
        DeviceCard = matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("hwmgrclient", "VisaDeviceCard")
        SettingsIcon = matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("ict", "Settings")
        HelpIcon = matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("ict", "Help")
    end

    %% Overridden hardware manager methods
    methods
        function devices = getDevices(obj)
            devices = createHwmgrDevices(obj);
        end

        function descriptor = getDeviceParamDescriptors(obj)
            % If NonEnumDescriptor has not been created, create it.
            if isempty(obj.NonEnumDescriptor)
                createNonEnumDescriptor(obj);
            end

            % Return the non-enum descriptor to Hardware Manager.
            descriptor = obj.NonEnumDescriptor;
        end

        function descriptor = getConfigureParamDescriptors(obj)
            % If DetectedDeviceDescriptor has not been created, create it.
            if isempty(obj.DetectedDeviceDescriptor)
                createDetectedDeviceDescriptor(obj);
            end

            % Return the enum descriptor to Hardware Manager.
            descriptor = obj.DetectedDeviceDescriptor;
        end
    end

    %% getDeviceParamDescriptors helper functions
    methods (Access = private)
        function createNonEnumDescriptor(obj)
            % Creates descriptor for non-enum devices created by the user.

            descriptor = ividevapp.NonEnumDescriptor();

            fieldLabel = @(msgLabel) message("ividevapp:ividevapp:" + msgLabel).getString();
            resourceSectionName = message("ividevapp:ividevapp:Resource").getString();

            % Interface Dropdown
            descriptor.addParameter('Interface', ...
                fieldLabel("Interface"), ...
                "DropDown", ...
                @descriptor.interfaceValuesFcn, ...
                function_handle.empty, ...
                resourceSectionName);

            % Resource Edit field
            descriptor.addParameter('ResourceName', ...
                fieldLabel("Resource"), ...
                "EditField", ...
                @descriptor.generateResourceNameChangeFcn, ...
                function_handle.empty, ...
                resourceSectionName);

            % Generate Resource Button
            [~, icon] = matlab.hwmgr.internal.data.plugins.InstrumentExplorerDataPlugin.getIconDetails("ToolstripIcon", obj.SettingsIcon);
            descriptor.addButton('GenerateResourceName', ...
                fieldLabel("GenerateResource"), ...
                icon, ...
                'Vertical', ...
                @descriptor.generateResourceNameValuesFcn, ...
                function_handle.empty, ...
                resourceSectionName);

            driverSectionName = message("ividevapp:ividevapp:Driver").getString();

            % Create descriptor params that are common for both non-enum
            % and enum ividevapp descriptors.
            descriptor = createBaseDescriptorParams(obj, descriptor, driverSectionName);

            obj.NonEnumDescriptor = descriptor;
        end

        function createDetectedDeviceDescriptor(obj)
            % Creates descriptor class for enum devices discovered by the user
            % when launching the ividevapp.

            descriptor = ividevapp.DetectedDeviceDescriptor();

            fieldLabel = @(msgLabel) message("ividevapp:ividevapp:" + msgLabel).getString();
            driverSectionName = message("ividevapp:ividevapp:ConnectionParamSection").getString();

            % Resource Edit field
            descriptor.addParameter('ResourceName', ...
                fieldLabel("Resource"), ...
                "NonEditableField", ...
                @(paramValMap)descriptor.deviceDetailsFcn(paramValMap, "ResourceName"), ...
                function_handle.empty, ...
                driverSectionName);

            % Model Edit field
            descriptor.addParameter('Model', ...
                fieldLabel("Model"), ...
                "NonEditableField", ...
                @(paramValMap)descriptor.deviceDetailsFcn(paramValMap, "Model"), ...
                function_handle.empty, ...
                driverSectionName);

            % SerialNumber Edit field
            descriptor.addParameter('SerialNumber', ...
                fieldLabel("SerialNumber"), ...
                "NonEditableField", ...
                @(paramValMap)descriptor.deviceDetailsFcn(paramValMap, "SerialNumber"), ...
                function_handle.empty, ...
                driverSectionName);

            % Create descriptor params that are common for both non-enum
            % and enum ividevapp descriptors.
            descriptor = createBaseDescriptorParams(obj, descriptor, driverSectionName);

            obj.DetectedDeviceDescriptor = descriptor;
        end

        function descriptor = createBaseDescriptorParams(obj, descriptor, driverSectionName)
            % Create descriptor params that are common for both non-enum
            % and enum ividevapp descriptors.

            fieldLabel = @(msgLabel) message("ividevapp:ividevapp:" + msgLabel).getString();

            % Driver Dropdown
            descriptor.addParameter('Drivers', ...
                fieldLabel("Driver"), ...
                "DropDown", ...
                @descriptor.driverValuesFcn, ...
                function_handle.empty, ...
                driverSectionName);

            % Class Compliant Dropdown
            descriptor.addParameter('ClassCompliant', ...
                fieldLabel("ClassCompliant"), ...
                "DropDown", ...
                @descriptor.classComValuesFcn, ...
                @descriptor.classComEnabledFcn, ...
                driverSectionName);

            % Dont See Your Driver Button
            [~, icon] = matlab.hwmgr.internal.data.plugins.InstrumentExplorerDataPlugin.getIconDetails("ToolstripIcon", obj.HelpIcon);
            descriptor.addButton('DontSeeYourDriver', ...
                fieldLabel("DontSeeYourDriver"), ...
                icon, ...
                'Vertical', ...
                @descriptor.launchDontSeeYourDriverPage, ...
                function_handle.empty, ...
                driverSectionName);

            optionalParamSectionName = message("ividevapp:ividevapp:OptionalParamSection").getString();

            % Simulate Dropdown
            descriptor.addParameter('Simulate', ...
                fieldLabel("Simulate"), ...
                "DropDown", ...
                @descriptor.falseTrueValuesFcn, ...
                function_handle.empty, ...
                optionalParamSectionName);

            % Cache Dropdown
            descriptor.addParameter('Cache', ...
                fieldLabel("Cache"), ...
                "DropDown", ...
                @descriptor.trueFalseValuesFcn, ...
                function_handle.empty, ...
                optionalParamSectionName);

            % Interchange Check Dropdown
            descriptor.addParameter('InterchangeCheck', ...
                fieldLabel("InterchangeCheck"), ...
                "DropDown", ...
                @descriptor.falseTrueValuesFcn, ...
                function_handle.empty, ...
                optionalParamSectionName);

            % Query Instrument Status Dropdown
            descriptor.addParameter('QueryInstrStatus', ...
                fieldLabel("QueryInstrStatus"), ...
                "DropDown", ...
                @descriptor.trueFalseValuesFcn, ...
                function_handle.empty, ...
                optionalParamSectionName);

            % Range Check Dropdown
            descriptor.addParameter('RangeCheck', ...
                fieldLabel("RangeCheck"), ...
                "DropDown", ...
                @descriptor.trueFalseValuesFcn, ...
                function_handle.empty, ...
                optionalParamSectionName);

            % Record Coercions Dropdown
            descriptor.addParameter('RecordCoercions', ...
                fieldLabel("RecordCoercions"), ...
                "DropDown", ...
                @descriptor.falseTrueValuesFcn, ...
                function_handle.empty, ...
                optionalParamSectionName);

            % ID Query Dropdown
            descriptor.addParameter('IDQuery', ...
                fieldLabel("IDQuery"), ...
                "DropDown", ...
                @descriptor.trueFalseValuesFcn, ...
                function_handle.empty, ...
                optionalParamSectionName);

            % Reset Device Dropdown
            descriptor.addParameter('ResetDevice', ...
                fieldLabel("ResetDevice"), ...
                "DropDown", ...
                @descriptor.falseTrueValuesFcn, ...
                function_handle.empty, ...
                optionalParamSectionName);

            % Timeout Edit Field
            descriptor.addParameter('Timeout', ...
                fieldLabel("Timeout"), ...
                "EditField", ...
                @descriptor.defaultTimeoutValueFcn, ...
                function_handle.empty, ...
                optionalParamSectionName);

            % Driver Setup Edit Field
            descriptor.addParameter('DriverSetup', ...
                fieldLabel("DriverSetup"), ...
                "EditField", ...
                function_handle.empty, ...
                function_handle.empty, ...
                optionalParamSectionName);

            % Additional Option String Edit Field
            descriptor.addParameter('OptionString', ...
                fieldLabel("OptionString"), ...
                "EditField", ...
                function_handle.empty, ...
                function_handle.empty, ...
                optionalParamSectionName);
        end
    end

    %% getDevices helper functions
    methods (Access = private)
        function devices = createHwmgrDevices(obj)
            import ividevapp.IvidevDeviceProvider

            % Creates hardware manager device cards for discovered
            % instruments that can be communicated with using IVI or
            % VXIplug&play drivers.

            devices = matlab.hwmgr.internal.Device.empty;

            try
                % Turn off warning for partially detected Visa resources
                % incase visadevlist is not able to detect all resources
                % within the Timeout specified.
                warnstate = warning;
                cleanupObj = onCleanup(@()warning(warnstate));
                warning("off", "instrument:interface:visa:timeoutExpiredPartialList");

                % Run visadevlist to get VISA resource, model, vendor,
                % serial number information for all discovered devices.
                visaResourceList = visadevlist("Timeout", 100);

                % Trigger onCleanup callback to reinstate original warning
                % state.
                clear cleanupObj
            catch
                % Error with visadevlist indicates VISA installation issue,
                % return early with empty device list.
                % This is needed for hardwareManager launch workflow.
                return
            end

            if isempty(visaResourceList)
                return
            end

            for i = 1:size(visaResourceList, 1)
                if visaResourceList.Model(i) == ""
                    % Not a test and measurement device. Model is needed
                    % for test and measurement devices.
                    continue
                end

                % Populate model and vendor name as device card title.
                vendorStr = visaResourceList.Vendor(i);
                deviceName = visaResourceList.Model(i) + blanks(1) + vendorStr;
                device = matlab.hwmgr.internal.Device(deviceName);

                [iconFieldName, icon] = matlab.hwmgr.internal.data.plugins.InstrumentExplorerDataPlugin.getIconDetails("DeviceCardOrAppletDataIcon", obj.DeviceCard);
                device.(iconFieldName) = icon;

                % Set DeviceEnumerableConfigData to true. This is needed
                % for DetectedDeviceDescriptor
                device.DeviceEnumerableConfigData = matlab.hwmgr.internal.data.DataFactory. ...
                    createDeviceEnumerableConfigData("ividevapp.IvidevApp", ...
                    "ividevapp.DetectedDeviceDescriptor", true);

                % Save the ResourceName to be used by the ividev app to
                % form a connection to the instrument.
                % Also save the Model and SerialNumber to display in the
                % configuration tab page.
                device.CustomData.ResourceName = visaResourceList.ResourceName(i);
                device.CustomData.Model = visaResourceList.Model(i);
                device.CustomData.SerialNumber = visaResourceList.SerialNumber(i);

                % Set the device UUID. This needs to be the same as
                % VisaExplorer if we want to show one combined card for
                % devices detected by both the app.
                device.UUID = compose("%s_%s", visaResourceList.ResourceName(i), visaResourceList.SerialNumber(i));

                % Set the information that will be displayed on the device
                % card below the title.
                deviceCardFirstRowDetails = [message("ividevapp:ividevapp:Resource").string, visaResourceList.ResourceName(i)];
                deviceCardSecondRowDetails = [message("ividevapp:ividevapp:SerialNumber").string, visaResourceList.SerialNumber(i)];

                device.DeviceCardDisplayInfo = [ ...
                    deviceCardFirstRowDetails; ...
                    deviceCardSecondRowDetails ...
                    ];

                device.DeviceAppletData = matlab.hwmgr.internal.data.DataFactory.createDeviceAppletData("ividevapp.IvidevApp", "IC");

                devices(end+1) = device; %#ok<AGROW>
            end
        end
    end
end